### ISSUE TITLE
have a question about progress bar

### ISSUE THREAD

**Issue by qimingWei** [videojs/thumbcoil#3]
i use video.js 5.11.8 
i find a bug, when i click progress bar to Fast forward to somewhere and i click progress bar back to other somewhere. After i click back off the progress bar will be return to the first i Fast forward point.
how can i Change it to normal ?

https://cloud.githubusercontent.com/assets/25046571/21961434/83e01588-db44-11e6-98ed-06068af17c13.gif

**Comment by nickygerritsen** [comment]
I think this has nothing to do with the settings menu, so you should probably file it in the `videojs/video.js` project instead of here
